# Generated by Django 4.2.19 on 2025-05-04 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productimagemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategorymodel',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ['-created_date']},
        ),
    ]
