# Generated by Django 4.2.19 on 2025-05-29 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_ordermodel_payment'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentModel',
        ),
    ]
